const Dishes = [
  {
    name: "Margherita Pizza",
    details: "Classic pizza with tomato sauce, mozzarella cheese, and basil.",
    price: 12.99,
    category: "Pizza",
    restaurant: "Fantastic Restaurant 1",
    status: "inactive",
    ingredients: [
      "Tomato Sauce",
      "Mozzarella Cheese",
      "Fresh Basil",
      "Pizza Dough",
    ],
    image: "/image/Plate/Image1.png",
  },
  {
    name: "Chicken Alfredo Pasta",
    details:
      "Creamy Alfredo sauce with grilled chicken and fettuccine noodles.",
    price: 15.99,
    category: "Pasta",
    restaurant: "Amazing Italian Kitchen",
    status: "active",
    ingredients: [
      "Tomato Sauce",
      "Mozzarella Cheese",
      "Fresh Basil",
      "Pizza Dough",
    ],
    image: "/image/Plate/Image2.png",
  },
  {
    name: "Caesar Salad",
    details:
      "Fresh romaine lettuce with Caesar dressing, croutons, and Parmesan cheese.",
    price: 8.99,
    category: "Salad",
    restaurant: "Healthy Bites",
    status: "inactive",
    ingredients: [
      "Tomato Sauce",
      "Mozzarella Cheese",
      "Fresh Basil",
      "Pizza Dough",
    ],
    image: "/image/1.png",
  },
  {
    name: "BBQ Burger",
    details:
      "Beef patty topped with BBQ sauce, cheddar cheese, lettuce, and tomato.",
    price: 10.99,
    category: "Burger",
    restaurant: "Burger Heaven",
    status: "active",
    ingredients: [
      "Tomato Sauce",
      "Mozzarella Cheese",
      "Fresh Basil",
      "Pizza Dough",
    ],
    image: "/image/8.png",
  },
  {
    name: "Vegetable Stir-Fry",
    details:
      "Assorted vegetables stir-fried with soy sauce and served with rice.",
    price: 11.99,
    category: "Burger",
    restaurant: "Wok Delight",
    status: "inactive",
    ingredients: [
      "Tomato Sauce",
      "Mozzarella Cheese",
      "Fresh Basil",
      "Pizza Dough",
    ],
    image: "/image/Plate/Image1.png",
  },
  {
    name: "Chocolate Brownie Sundae",
    details:
      "Warm chocolate brownie topped with vanilla ice cream and chocolate syrup.",
    price: 6.99,
    category: "Dessert",
    restaurant: "Sweet Delights",
    status: "inactive",
    ingredients: [
      "Tomato Sauce",
      "Mozzarella Cheese",
      "Fresh Basil",
      "Pizza Dough",
    ],
    image: "/image/Plate/Image1.png",
  },
  {
    name: "Iced Coffee",
    details:
      "Chilled coffee served with ice and your choice of cream and sweeteners.",
    price: 3.99,
    category: "Sushi",
    restaurant: "Cafe Oasis",
    status: "inactive",
    ingredients: [
      "Tomato Sauce",
      "Mozzarella Cheese",
      "Fresh Basil",
      "Pizza Dough",
    ],
    image: "/image/Plate/Image1.png",
  },
  {
    name: "Sushi Platter",
    details: "Assortment of fresh sushi rolls and sashimi.",
    price: 18.99,
    category: "Sushi",
    restaurant: "Sushi Master",
    status: "active",
    ingredients: [
      "Tomato Sauce",
      "Mozzarella Cheese",
      "Fresh Basil",
      "Pizza Dough",
    ],
    image: "/image/Plate/Image1.png",
  },
  {
    name: "Grilled Steak",
    details:
      "Tender grilled steak served with garlic mashed potatoes and vegetables.",
    price: 22.99,
    category: "Steak",
    restaurant: "Steakhouse Royale",
    status: "active",
    ingredients: [
      "Tomato Sauce",
      "Mozzarella Cheese",
      "Fresh Basil",
      "Pizza Dough",
    ],
    image: "/image/Plate/Image1.png",
  },
  {
    name: "Mediterranean Wrap",
    details:
      "A wrap filled with Mediterranean flavors, including hummus and grilled veggies.",
    price: 9.99,
    category: "Sushi",
    restaurant: "Mediterranean Eats",
    status: "inactive",
    ingredients: [
      "Tomato Sauce",
      "Mozzarella Cheese",
      "Fresh Basil",
      "Pizza Dough",
    ],
    image: "/image/Plate/Image1.png",
  },
  {
    name: "Pho Noodle Soup",
    details:
      "Vietnamese noodle soup with beef or chicken, fresh herbs, and rice noodles.",
    price: 10.49,
    category: "Sushi",
    restaurant: "Pho Express",
    status: "active",
    ingredients: [
      "Tomato Sauce",
      "Mozzarella Cheese",
      "Fresh Basil",
      "Pizza Dough",
    ],
    image: "/image/Plate/Image1.png",
  },
  {
    name: "Vegan Quinoa Bowl",
    details:
      "A healthy and delicious vegan bowl with quinoa, vegetables, and tahini dressing.",
    price: 13.99,
    category: "Bowl",
    restaurant: "Green Haven",
    status: "active",
    ingredients: [
      "Tomato Sauce",
      "Mozzarella Cheese",
      "Fresh Basil",
      "Pizza Dough",
    ],
    image: "/image/Plate/Image1.png",
  },
  {
    name: "Fish and Chips",
    details: "Crispy battered fish served with french fries and tartar sauce.",
    price: 14.99,
    category: "Seafood",
    restaurant: "Fisherman's Cove",
    status: "active",
    ingredients: [
      "Tomato Sauce",
      "Mozzarella Cheese",
      "Fresh Basil",
      "Pizza Dough",
    ],
    image: "/image/Plate/Image1.png",
  },
  {
    name: "Taco Platter",
    details: "A variety of tacos with your choice of fillings and toppings.",
    price: 10.99,
    category: "Tacos",
    restaurant: "Taco Fiesta",
    status: "inactive",
    ingredients: [
      "Tomato Sauce",
      "Mozzarella Cheese",
      "Fresh Basil",
      "Pizza Dough",
    ],
    image: "/image/Plate/Image1.png",
  },
  {
    name: "Pad Thai Noodles",
    details: "Stir-fried rice noodles with shrimp or tofu, peanuts, and lime.",
    price: 12.99,
    category: "Tacos",
    restaurant: "Thai Delight",
    status: "active",
    ingredients: [
      "Tomato Sauce",
      "Mozzarella Cheese",
      "Fresh Basil",
      "Pizza Dough",
    ],
    image: "/image/Plate/Image1.png",
  },
];

export default Dishes;
