const Restos = [
  {
    name: "Obinasom",
    location: "South, Huye",
    contact: "07886337833",
    email: "Obinasom@gmail.com",
    decision: "rejected",
  },
  {
    name: "Obinasom",
    location: "Kigali, Nyarugenge",
    contact: "07886337833",
    email: "Obinasom@gmail.com",
    decision: "approved",
  },
  {
    name: "4B2 Resto",
    location: "South, Nyanza",
    contact: "07886337833",
    email: "4B2Resto@gmail.com",
    decision: "approved",
  },
  {
    name: "Villa",
    location: "South, Huye",
    contact: "07886337833",
    email: "Villa@gmail.com",
    decision: "pending",
  },
  {
    name: "Muhazi",
    location: "West, Rwamagana",
    contact: "07886337833",
    email: "Muhazi@gmail.com",
    decision: "rejected",
  },
  {
    name: "Eagle Resto",
    location: "Noth, Burera",
    contact: "07886337833",
    email: "eagleresto@gmail.com",
    decision: "pending",
  },
  {
    name: "Innove",
    location: "South, Huye",
    contact: "07886337833",
    email: "Innove@gmail.com",
    decision: "approved",
  },
  {
    name: "4B2 Resto",
    location: "South, Nyanza",
    contact: "07886337833",
    email: "4B2Resto@gmail.com",
    decision: "approved",
  },
  {
    name: "Villa",
    location: "South, Huye",
    contact: "07886337833",
    email: "Villa@gmail.com",
    decision: "pending",
  },
  {
    name: "Muhazi",
    location: "West, Rwamagana",
    contact: "07886337833",
    email: "Muhazi@gmail.com",
    decision: "rejected",
  },
  {
    name: "Eagle Resto",
    location: "Noth, Burera",
    contact: "07886337833",
    email: "eagleresto@gmail.com",
    decision: "pending",
  },
  {
    name: "Innove",
    location: "South, Huye",
    contact: "07886337833",
    email: "Innove@gmail.com",
    decision: "approved",
  },
  {
    name: "Ebis",
    location: "South, Huye",
    contact: "07886337833",
    email: "Ebis@gmail.com",
    decision: "rejected",
  },
  {
    name: "144",
    location: "South, Huye",
    contact: "07886337833",
    email: "onefourfour@gmail.com",
    decision: "pending",
  },
  {
    name: "Tousaint",
    location: "South, Huye",
    contact: "07886337833",
    email: "tousaint@gmail.com",
    decision: "rejected",
  },
  {
    name: "Upendi",
    location: "South, Huye",
    contact: "07886337833",
    email: "Upendipub@gmail.com",
    decision: "approved",
  },
  {
    name: "Restos11",
    location: "South, Huye",
    contact: "07886337833",
    email: "reconfortdanny@gmail.com",
    decision: "pending",
  },
];

export default Restos;
