const Users = [
  {
    username: "John",
    firstname: "John",
    lastname: "Muhoza",
    email: "John@gmail.com",
    location: "Huye, South",
    phone: "078837833",
    UserType: "client",
  },
  {
    username: "Alice",
    firstname: "Alice",
    lastname: "Smith",
    email: "alice@gmail.com",
    location: "New York, USA",
    phone: "123456789",
    UserType: "mini-admin",
  },
  {
    username: "Bob",
    firstname: "Bob",
    lastname: "Johnson",
    email: "bob@gmail.com",
    location: "Los Angeles, USA",
    phone: "987654321",
    UserType: "mini-admin",
  },
  {
    username: "James",
    firstname: "James",
    lastname: "Wright",
    email: "james@gmail.com",
    location: "Seoul, South Korea",
    phone: "555555555",
    UserType: "client",
  },
  {
    username: "Ava",
    firstname: "Ava",
    lastname: "Parker",
    email: "ava@gmail.com",
    location: "Beijing, China",
    phone: "999999999",
    UserType: "client",
  },
  {
    username: "Noah",
    firstname: "Noah",
    lastname: "Hall",
    email: "noah@gmail.com",
    location: "Sao Paulo, Brazil",
    phone: "777777777",
    UserType: "client",
  },
  {
    username: "Noah",
    firstname: "Noah",
    lastname: "Hall",
    email: "noah@gmail.com",
    location: "Sao Paulo, Brazil",
    phone: "777777777",
    UserType: "client",
  },
];

export default Users;
